services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  web:
    build: .
    ports:
      - '8000:8000'
    command: python project/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    depends_on:
      - postgres

    
volumes:
  postgres_data: