[tool.poetry]
name = "url-shortener"
version = "0.1.0"
description = ""
authors = ["Orlovchik <svetl.orlovaa@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
Django = "^5.1"
psycopg2-binary = "^2.9.9"
requests = "^2.32.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
