# Generated by Django 5.1 on 2024-08-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Short_url',
            fields=[
                ('original_url', models.URLField(max_length=700)),
                ('short_url', models.CharField(primary_key=True, serialize=False)),
                ('datatime_created', models.DateTimeField()),
            ],
        ),
    ]
