# Generated by Django 5.1 on 2024-08-20 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Short_url',
            new_name='ShortUrl',
        ),
    ]
